#!/bin/bash

deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

sed -i "s/rcmail-ynhDESkeyTOchange/$deskey/g" $APPDIR/config/main.inc.php
sed -i "s/yunouser/$MYSQL_USER/g" $APPDIR/config/db.inc.php
sed -i "s/yunopass/$MYSQL_PWD/g" $APPDIR/config/db.inc.php
sed -i "s/yunobase/$MYSQL_DB/g" $APPDIR/config/db.inc.php
